# introduction
# boolean true or false 
# or true and true = true
# """  true or false = true 
#  or false or true = true 
#  true or true = true 
# false or false =false 
# and  
# false and true = false
# true and true = true 
# false and false =false 
# """
# print(3==3 and 3 == 5)
#  if ,elif and else
# price = 100
# if price > 90:
#     print('expensive')
# elif price > 70:
#     print('normal')
# elif price > 60:
#     print('cheap')
# else:
#     print('none')
