# introduction
""" 
conditions 
logic and or and not
comparison =< >= == !=
boolean true and false
# 
or
true or true=true 
false or true =true
true and false =true
false or false = false

and
true and true =true
false and true = false
true and false =false
false and false = false
not 
false = true
true = false

"""


# <----> */ *
print(4== 5 or 6 > 5)
print(4== 5 and 6 > 5)
print(4== 4 and not 4 > 5)
# price = 70
# if price > 90:
#     print('expansive')
# elif price > 70:
#     print('normal')
# elif price < 60:
#     print('cheap')
# else:
#     print('none')
